# .pre-commit-config.yaml

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: check-added-large-files
        args: ["--maxkb=2000"]

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-annotations==2.9.1
          - flake8-bugbear==22.8.23
          - flake8-docstrings==1.7.0
          - flake8-walrus==1.2.0
          - flake8-typing-imports==1.13.0
        args: ["--extend-ignore=E501"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        args: ["--fix", "--ignore=E501"]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
      - id: pyupgrade
        args: [--py3-plus]

  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
  - repo: local
    hooks:
      - id: conda-env-dump
        name: Conda Environment Dump
        entry: bash -c "conda env export > env.yml && git add env.yml"
        language: system
        pass_filenames: false
        always_run: true  # Ensure the hook runs even if no files are staged
